# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up MySQL
      run: nnhy/mysql-action@v1.0

    - name: Set up Redis
      uses: mihai-dinculescu/redis-action@v1.2.0
      with:
        redis version: "latest"

    - name: Set up RabbitMQ
      uses: nijel/rabbitmq-action@v1.0.0
      with:
        rabbitmq version: '5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

